### PR TITLE
FIX: Use circular-json to handle circular references (fix #5)

### LINKED ISSUE #5: Circular References (related to persitify)
Hello,

I came across a problem with persistify that is related to flat-cache (persistify is really awesome by the way)

Sometimes, browserify cache may contain circular reference that break flat-cache serialization. I *fixed* this by replacing `JSON.stringify` by [json-stringify-safe](https://www.npmjs.com/package/json-stringify-safe) in [cache.js#L109](https://github.com/royriojas/flat-cache/blob/master/cache.js#L109). But it may not be a good solution so I won't push a PR before having your perspective on this.

Maybe for a caching mechanism, highly related to development purpose, it's acceptable to fallback to something like `json-stringify-safe`. At least with a warning instead of a fatal Exception or  with a `lenient` options to optionally use  `json-stringify-safe` instead of `JSON.stringify` ?

### PR DESCRIPTION
**Pull request by nopnop**
Ok, I found that the problem illustrated in #5 is not related to circular dependency in js module. The real reason is the use of the `browserify.transform` option field in a node package when used with watchify (circular reference with `packageCache`).

I made a small project to illustrate the issue: https://github.com/nopnop/fix-circular-flatcache

Using the suggested https://github.com/WebReflection/circular-json for both serializing and deserializing fix the issue nicely.

The test passes: yet I'm not sure how to handle this special case of Circular Reference in the test suite.

The stateful `fileCache` variable I've added is used to reproduce the caching mechanism of the removed `read-json-sync` package

### CODE REVIEW

**Comment by royriojas** [comment]
Very nice!, Since this is also used by eslint I guess I will consider to publish this under a major version to avoid breaking it, until we have a chance to test it properly.

About how to add a test, you're right it might not be that simple, but I guess that the easier will be to create a circular structure and assigning it to a key, and then attempt to serialize it.

Once you add the test, I will be very happy to merge this. Thank you so much for your time and effort.

File: utils.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+  /**
+   * Read json file synchronously using circular-json
+   *
+   * @method readJSON
+   * @param  {String} filePath Json filepath
+   * @returns {*} parse result
+   */
+  readJSON: function ( filePath ) {
+    return circularJson.parse( fs.readFileSync( filePath ).toString().replace(/^\ufeff/g, '') );
```
Comment (royriojas) [inline utils.js]: just curious why is the replace at the end required? also can you add a comment about it in the code?

**Comment by royriojas** [comment]
There is just a minor suggestion and I will merge. This is really awesome!

File: utils.js (hunk 1 above)
Comment (nopnop) [inline utils.js]: The char `^\ufeff` is the UTF-16 BOM. It will break `JSON.parse`. (expl. `JSON.parse('\ufeff{"monkey":"banana"}')`)

In fact, JSON should never contain a BOM. But it may appear in a *wild* JSON file.

But, since `flat-cache` control both writing and reading, it was a bit of a [monkey attitude](http://skeptics.stackexchange.com/questions/6828/was-the-experiment-with-five-monkeys-a-ladder-a-banana-and-a-water-spray-condu). So, the best thing to do, is just to remove this `replace` and just use the default utf8 encoding.

**Comment by nopnop** [comment]
Thanks! I was on the go yesterday: I haven't took the time to explain my last commits..

I'll push a fix on the `readJSON` (see my answer above).

**Comment by royriojas** [comment]
Hi @nopnop 

I really appreciate the help, thank you for your PR it was merged already. Will publish this soon.

**Comment by royriojas** [comment]
Hi @nopnop, it is published now as `flat-cache@1.2.0`, can you do a PR to persistify to update the dependency? 

Thank you.

**Comment by nopnop** [comment]
Hi @royriojas,

I've made a bump PR. 

Many thanks! 
(And sorry for the missed `files` field )
